services:
  axonserver-1:
    image: axoniq/axonserver:latest-jdk-17
    pull_policy: always
    environment:
# tag::console[]
      - axoniq_console_authentication=YOUR_ACCESS_TOKEN
# end::console[]
# tag::enterprise[]
      - axoniq_axonserver_autocluster_first=axonserver-1
      - axoniq_axonserver_autocluster_contexts=_admin,default
# end::enterprise[]
      - axoniq_axonserver_name=axonserver-1
      - axoniq_axonserver_hostname=localhost
      - axoniq_axonserver_internal_hostname=axonserver-1
      - server_port=8024
      - axoniq_axonserver_port=8124
      - axoniq_axonserver_internal_port=8224
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
# tag::enterprise[]
    volumes:
      - ./axoniq-server.license:/axonserver/config/axoniq.license
# end::enterprise[]

  axonserver-2:
    image: axoniq/axonserver:latest-jdk-17
    pull_policy: always
    environment:
      # tag::console[]
      - axoniq_console_authentication=YOUR_ACCESS_TOKEN
      # end::console[]
      # tag::enterprise[]
      - axoniq_axonserver_autocluster_first=axonserver-1
      - axoniq_axonserver_autocluster_contexts=_admin,default
      # end::enterprise[]
      - axoniq_axonserver_hostname=localhost
      - axoniq_axonserver_internal_hostname=axonserver-2
      - server_port=8025
      - axoniq_axonserver_port=8125
      - axoniq_axonserver_internal_port=8225
    ports:
      - '8025:8025'
      - '8125:8125'
      - '8225:8225'
# tag::enterprise[]
    volumes:
      - ./axoniq-server.license:/axonserver/config/axoniq.license
  # end::enterprise[]

  axonserver-3:
    image: axoniq/axonserver:latest-jdk-17
    pull_policy: always
    environment:
      # tag::console[]
      - axoniq_console_authentication=YOUR_ACCESS_TOKEN
      # end::console[]
      # tag::enterprise[]
      - axoniq_axonserver_autocluster_first=axonserver-1
      - axoniq_axonserver_autocluster_contexts=_admin,default
      # end::enterprise[]
      - axoniq_axonserver_hostname=localhost
      - axoniq_axonserver_internal_hostname=axonserver-3
      - server_port=8026
      - axoniq_axonserver_port=8126
      - axoniq_axonserver_internal_port=8226
    ports:
      - '8026:8026'
      - '8126:8126'
      - '8226:8226'
# tag::enterprise[]
    volumes:
      - ./axoniq-server.license:/axonserver/config/axoniq.license
# end::enterprise[]