services:
  axonserver-1:
    image: axoniq/axonserver:latest-jdk-17
    pull_policy: always
    environment:
# tag::console[]
      - axoniq_console_authentication=YOUR_ACCESS_TOKEN
# end::console[]
      - axoniq_axonserver_hostname=localhost
      - axoniq_axonserver_internal_hostname=axonserver-1
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'