version: 2

updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
  open-pull-requests-limit: 5
  labels:
    - "Type: Dependency Upgrade"
    - "Priority 1: Must"
  reviewers:
    - "BraininaBowl"
    - "bruceaxoniq"
    - "CodeDrivenMitch"
    - "smcvb"
    - "trimoq"
  groups:
    github-dependencies:
      update-types:
        - "patch"
        - "minor"
        - "major"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: "sunday"
  open-pull-requests-limit: 5
  labels:
    - "Type: Dependency Upgrade"
    - "Priority 1: Must"
  reviewers:
    - "BraininaBowl"
    - "bruceaxoniq"
    - "CodeDrivenMitch"
    - "smcvb"
    - "trimoq"
  groups:
    maven-dependencies:
      update-types:
        - "patch"
        - "minor"
        - "major"