= Installing Axon Server

Axon Server is the most efficient messaging platform and event storage solution for your Axon Framework applications.
Before installation, make sure you know which edition you want to run, as it's important to choose the right one for your needs.

== Available guides

You can choose your edition below and the method of installation you want to use.

|===
|Edition ^|Cost ^|Acquisition  | Guides

|xref:developer/index.adoc[Axoniq Developer]
^|Free
^|link:https://console.axoniq.io[Axoniq Console]
a|
* xref:developer/download.adoc[Download]
* xref:developer/docker.adoc[Docker]
* xref:developer/docker-compose.adoc[Docker Compose]
* xref:developer/kubernetes.adoc[Kubernetes]
* xref:developer/linux.adoc[Linux]

|xref:professional/index.adoc[Axoniq Professional]
^|From 40$/month
^|link:https://console.axoniq.io[Axoniq Console]
a|
* xref:professional/download.adoc[Download]
* xref:professional/docker-compose.adoc[Docker Compose]
* xref:professional/kubernetes.adoc[Kubernetes]
* xref:professional/linux.adoc[Linux]

|xref:enterprise/index.adoc[Axoniq Enterprise]
^|Contract
^|link:https://www.axoniq.io/contact[Contact us]
a|
* xref:enterprise/download.adoc[Download]
* xref:enterprise/docker-compose.adoc[Docker Compose]
* xref:enterprise/kubernetes.adoc[Kubernetes]
* xref:enterprise/linux.adoc[Linux]

|===

For a full comparison on features, please consult our link:https://www.axoniq.io/pricing[pricing page].

== Updating Axon Server

Did Axoniq release a new version, and do you want to upgrade your Axon Server to a later version?
We have a guide for you.

* xref:updating/index.adoc[Updating Axon Server]

== Migrations

Are you coming from a non-Axon Server environment?
We have a migration guide for you.

* xref:migrations/to-axon-server.adoc[Other databases to Axon Server]
* xref:migrations/from-axon-server.adoc[Axon Server to other databases]
