site:
  title: Docs
  url: /
  start_page: home::index.adoc
urls:
  # Enabling html_extension_style will make URLs more user-friendly, but will break it during local dev usage
  html_extension_style: indexify
  redirect_facility: static

content:
  sources:
  - url: .
    start_paths: content/*

  - url: ./localLinks/AxonFramework/          # include docs from Axon Framework repo
    start_paths: ['docs/*', '!docs/_*', '!docs/reference/*']       # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-amqp/          # include docs from Axon AMQP Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-jgroups/       # include docs from Axon JGroups Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-jobrunrpro/    # include docs from Axon JobRunr Pro Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-kafka/         # include docs from Axon Kafka Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-kotlin/         # include docs from Axon Kotlin Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-mongo/         # include docs from Axon Mongo Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-multitenancy/  # include docs from Axon Multitenancy Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-reactor/         # include docs from Axon Reactor Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-spring-aot/    # include docs from Axon Spring AOT Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-springcloud/   # include docs from Axon Spring Cloud Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-tracing/       # include docs from Axon Tracing Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/axon-server/             # include docs from Axon Server repo
    start_paths: ['docs/*', '!docs/_*', '!docs/as-fundamentals-tutorial']       # from every folder in `docs` except those starting with underscore
# #    branches: [master, 'axonserver-ee-20*']   # and from the specified branches

  - url: ./localLinks/axon-server-image-build/ # include docs from Image generation for Axon Server repo (which contiains docs about Axon Server GCP marketplace)
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore
# #    branches: [master, 'axonserver-ee-20*'] # and from the specified branches

  - url: ./localLinks/axon-synapse/            # include docs from Axon Synapse repo
    start_paths: ['docs/*', '!docs/_*']       # from every folder in `docs` except those starting with underscore
  #   branches: [development, 'synapse-*']      # and from the specified branches

  - url: ./localLinks/console-web/           # include docs from AxonIQ Console
    start_paths: ['docs/*', '!docs/_*']       # from every folder in `docs` except those starting with underscore
  #   branches: [master, docs]

  - url: ./localLinks/bike-rental-quick-start/ # include docs from BikeRental Demo app
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  # - url: .
  #   start_paths: external_repos/axon_server/docs/*
  # - url: .
  #   start_paths: external_repos/axoniq_cloud/docs/*

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
  - '@asciidoctor/tabs'

antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js
  - id: prose-linting
    require: '@axoniq/antora-vale-extension'
    enabled: true
    vale_config: .vale.dev.ini
    update_styles: true
  - id: lunr
    require: '@antora/lunr-extension'
    enabled: true
    index_latest_only: true

runtime:
  fetch: true # fetch remote repos
  log:
    level: debug
    failure_level: error

ui:
  bundle:
    url: https://github.com/AxonIQ/axoniq-library-ui/releases/download/v.0.1.46/ui-bundle.zip
