site:
  title: 📚 AxonIQ Library
  url: /
  start_page: home::index.adoc

content:
  sources:
  - url: .
    start_paths: components/*
  - url: .
    start_paths: ['localLinks/AxonFramework/docs/*', '!localLinks/AxonFramework/docs/playbook']
  - url: .
    start_paths: ['localLinks/giftcard-demo/docs/*', '!localLinks/giftcard-demo/docs/playbook']
  # - url: .
  #   start_paths: external_repos/axon_framework/*/docs/*
  # - url: .
  #   start_paths: external_repos/axon_server/docs/*
  # - url: .
  #   start_paths: external_repos/axoniq_cloud/docs/*
  # - url: .
  #   start_path: external_repos/giftcard-demo/docs

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    kroki-fetch-diagram: false
  extensions:
  - asciidoctor-kroki

antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js
  - id: prose-linting
    require: ./extensions/vale.js
    enabled: true
    vale_config: .vale.dev.ini
  - id: lunr
    require: '@antora/lunr-extension'
    enabled: true
    index_latest_only: true

runtime:
  fetch: true # fetch remote repos
  log:
    level: debug
    failure_level: error

ui:
  bundle:
    url: localLinks/UI/build/ui-bundle.zip
