site:
  title: Docs
  url: /
  start_page: home::index.adoc

content:
  sources:
  - url: .
    start_paths: content/*

  - url: ./localLinks/AxonFramework/          # include docs from Axon Framework repo
    start_paths: ['docs/*', '!docs/_*']       # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-amqp/          # include docs from Axon AMQP Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-jgroups/       # include docs from Axon JGroups Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-jobrunrpro/    # include docs from Axon JobRunr Pro Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-kafka/         # include docs from Axon Kafka Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-kotlin/         # include docs from Axon Kotlin Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-mongo/         # include docs from Axon Mongo Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-multitenancy/  # include docs from Axon Multitenancy Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-reactor/         # include docs from Axon Reactor Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/extension-springcloud/   # include docs from Axon Spring Cloud Extension repo
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore

  - url: ./localLinks/axon-server/             # include docs from Axon Server repo
    start_paths: ['docs/*', '!docs/_*']       # from every folder in `docs` except those starting with underscore
#    branches: [master, 'axonserver-ee-20*']   # and from the specified branches

  - url: ./localLinks/axon-synapse/            # include docs from Axon Synapse repo
    start_paths: ['docs/*', '!docs/_*']       # from every folder in `docs` except those starting with underscore
  #   branches: [development, 'synapse-*']      # and from the specified branches

  - url: ./localLinks/console-web/           # include docs from AxonIQ Console
    start_paths: ['docs/*', '!docs/_*']       # from every folder in `docs` except those starting with underscore
  #   branches: [master, docs]

  - url: ./localLinks/bike-rental-quick-start/ # include docs from BikeRental Demo app
    start_paths: ['docs/*', '!docs/_*']        # from every folder in `docs` except those starting with underscore


  # - url: .
  #   start_paths: external_repos/axon_server/docs/*
  # - url: .
  #   start_paths: external_repos/axoniq_cloud/docs/*

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    kroki-fetch-diagram: false
  extensions:
  - asciidoctor-kroki
  - '@asciidoctor/tabs'

antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js
  - id: prose-linting
    require: '@axoniq/antora-vale-extension'
    enabled: true
    vale_config: .vale.dev.ini
    update_styles: true
  - id: lunr
    require: '@antora/lunr-extension'
    enabled: true
    index_latest_only: true

runtime:
  fetch: true # fetch remote repos
  log:
    level: debug
    failure_level: error

ui:
  bundle:
    url: localLinks/axoniq-library-ui/build/ui-bundle.zip
