site:
  title: 📚 AxonIQ Library
  url: https://library.axoniq.io
  start_page: home::index.adoc

content:
  sources:
  - url: .
    start_paths: components/*
  - url: https://github.com/azzazzel/AxonFramework.git
    start_paths: ['docs/*', '!docs/playbook']
  - url: https://github.com/azzazzel/giftcard-demo.git
    start_paths: ['docs/*', '!docs/playbook']
  # - url: .
  #   start_paths: external_repos/axon_framework/*/docs/*
  # - url: .
  #   start_paths: external_repos/axon_server/docs/*
  # - url: .
  #   start_paths: external_repos/axoniq_cloud/docs/*
  # - url: .
  #   start_path: external_repos/giftcard-demo/docs

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki

antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js
  - id: prose-linting
    require: ./extensions/vale.js
    enabled: true
    vale_config: .vale.ini
  - id: lunr
    require: '@antora/lunr-extension'
    enabled: true
    index_latest_only: true

runtime:
  fetch: true # fetch remote repos
  log:
    level: info
    failure_level: error

ui:
  bundle:
    url: https://github.com/AxonIQ/docs-ui/releases/download/v0.0.3/ui-bundle.zip
