site:
  title: 📚 AxonIQ Library
  start_page: home::index.adoc

content:
  sources:
  - url: .
    start_paths: components/*
  - url: .
    start_paths: external_repos/axon_framework/*/docs/*
  - url: .
    start_paths: external_repos/axon_server/docs/*
  - url: .
    start_paths: external_repos/axoniq_cloud/docs/*
  - url: .
    start_path: external_repos/giftcard-demo/docs
  - url: https://github.com/azzazzel/axoniq-reference-guide.git
    branches: kramdoc

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki

# ui:
#   bundle:
#     url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
#     snapshot: true
antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js
  - id: prose-linting
    require: ./extensions/vale.js
    enabled: true
    vale_config: .vale.ini

ui:
  bundle:
    url: https://github.com/AxonIQ/docs-ui/releases/download/v0.0.3/ui-bundle.zip
