site:
  title: 📚 AxonIQ Library
  url: /
  start_page: home::index.adoc

content:
  sources:
  - url: .
    start_paths: content/*
  - url: ./localLinks/AxonFramework/
    start_paths: ['docs/*', '!docs/_playbook']
  - url: ./localLinks/AxonSynapse/
    start_paths: ['docs/*', '!docs/_playbook']
    branches: [development, 'synapse-*']
  - url: ./localLinks/giftcard-demo/
    start_paths: ['docs/*', '!docs/_playbook']
  # - url: .
  #   start_paths: external_repos/axon_server/docs/*
  # - url: .
  #   start_paths: external_repos/axoniq_cloud/docs/*

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    kroki-fetch-diagram: false
  extensions:
  - asciidoctor-kroki
  - '@asciidoctor/tabs'

antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js
  - id: prose-linting
    require: '@axoniq/antora-vale-extension'
    enabled: true
    vale_config: .vale.dev.ini
    update_styles: true
  - id: lunr
    require: '@antora/lunr-extension'
    enabled: true
    index_latest_only: true

runtime:
  fetch: true # fetch remote repos
  log:
    level: debug
    failure_level: error

ui:
  bundle:
    url: localLinks/UI/build/ui-bundle.zip
