site:
  title: Axon Library
  start_page: home::index.adoc

content:
  sources:
  - url: .
    start_paths: components/*
  - url: .
    start_paths: external_repos/axon_framework/*/docs/*
  - url: .
    start_paths: external_repos/axon_server/docs/*
  - url: .
    start_paths: external_repos/axoniq_cloud/docs/*
  - url: .
    start_path: external_repos/giftcard-demo/docs


asciidoc:
  attributes:
    experimental: true


# ui:
#   bundle:
#     url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
#     snapshot: true

ui:
  bundle:
    url: https://github.com/AxonIQ/docs-ui/releases/download/v.0.0.1/ui-bundle.zip