site:
  title: 📚 AxonIQ Library
  url: https://library.axoniq.io
  start_page: home::index.adoc
  keys:
    google_tag_manager: 'GTM-5QD58ZB'
    # google_analytics: 'G-Z9N4KWZGQV'

content:
  sources:
  - url: .
    start_paths: content/*
    edit_url: https://github.com/AxonIQ/axoniq-library-site/edit/{refname}/{path}

  - url: https://github.com/AxonFramework/AxonFramework.git   # include docs from Axon Framework repo
    start_paths: ['docs/*', '!docs/_*']                       # from every folder in `docs` except those starting with underscore

  - url: https://github.com/AxonIQ/axon-server.git            # include docs from Axon Server repo
    start_paths: ['docs/*', '!docs/_*']                       # from every folder in `docs` except those starting with underscore
#    branches: [master, 'axonserver-ee-20*']                   # and from the specified branches
    branches: [master]

  - url: https://github.com/AxonIQ/axon-synapse.git           # include docs from Axon Synapse repo
    start_paths: ['docs/*', '!docs/_*']                       # from every folder in `docs` except those starting with underscore
    branches: [development, 'synapse-*']                      # and from the specified branches

  - url: https://github.com/AxonIQ/giftcard-demo.git          # include docs from Gift Card Demo repo
    start_paths: ['docs/*', '!docs/_*']                       # from every folder in `docs` except those starting with underscore

  # - url: .
  #   start_paths: external_repos/axon_server/docs/*
  # - url: .
  #   start_paths: external_repos/axoniq_cloud/docs/*

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    # temporary disable fetching diagrams at build time due to kroki server issues
    #kroki-fetch-diagram: false
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
  - '@asciidoctor/tabs'

antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js
  - id: prose-linting
    require: '@axoniq/antora-vale-extension'
    enabled: true
    vale_config: .vale.ini
    update_styles: true
  - id: lunr
    require: '@antora/lunr-extension'
    enabled: true
    index_latest_only: true
  # build a site manifest to be used by partial builds
  - id: atlas
    require: '@antora/atlas-extension'

runtime:
  fetch: true # fetch remote repos
  log:
    level: info
    failure_level: error

ui:
  bundle:
    url: https://github.com/AxonIQ/axoniq-library-ui/releases/download/v.0.1.0/ui-bundle.zip