site:
  title: 📚 AxonIQ Library
  url: https://library.axoniq.io
  start_page: home::index.adoc
  keys:
    google_tag_manager: 'GTM-5QD58ZB'
    # google_analytics: 'G-Z9N4KWZGQV'

content:
  sources:
  - url: .
    start_paths: content/*
    edit_url: https://github.com/AxonIQ/axoniq-library-site/edit/{refname}/{path}
  - url: https://github.com/AxonFramework/AxonFramework.git
    start_paths: ['docs/*', '!docs/_playbook']
  - url: https://github.com/AxonIQ/axon-synapse.git
    start_paths: ['docs/*', '!docs/_playbook']
    branches: [development, 'synapse-*']
  - url: https://github.com/AxonIQ/giftcard-demo.git
    start_paths: ['docs/*', '!docs/_playbook']
  # - url: .
  #   start_paths: external_repos/axon_server/docs/*
  # - url: .
  #   start_paths: external_repos/axoniq_cloud/docs/*

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    # temporary disable fetching diagrams at build time due to kroki server issues
    kroki-fetch-diagram: false
  extensions:
  - asciidoctor-kroki

antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js
  - id: prose-linting
    require: '@axoniq/antora-vale-extension'
    enabled: true
    vale_config: .vale.ini
    update_styles: true
  - id: lunr
    require: '@antora/lunr-extension'
    enabled: true
    index_latest_only: true

runtime:
  fetch: true # fetch remote repos
  log:
    level: info
    failure_level: error

ui:
  bundle:
    url: https://github.com/AxonIQ/axoniq-library-ui/releases/latest/download/ui-bundle.zip
