site:
  title: Docs
  url: https://docs.axoniq.io
  start_page: home::index.adoc
  keys:
    google_tag_manager: 'GTM-5QD58ZB'

urls:
  html_extension_style: indexify
  redirect_facility: static

content:
  sources:
  - url: .
    start_paths: content/*
    edit_url: https://github.com/AxonIQ/axoniq-library-site/edit/{refname}/{path}

  - url: https://github.com/AxonFramework/AxonFramework.git   # include docs from Axon Framework repo
    start_paths: ['docs/*', '!docs/_*']                       # from every folder in `docs` except those starting with underscore
    branches: [master, 'axon-*', '!axon-{1..3}.*', '!axon-4.{0..9}.x', '!axon-5.*']

  - url: https://github.com/AxonFramework/extension-amqp.git   # include docs for Axon AMQP Extension repo 
    start_paths: ['docs/*', '!docs/_*']                        # from every folder in `docs` except those starting with underscore
    branches: [master, 'axon-amqp-*', '!axon-amqp-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-jgroups.git  # include docs for Axon JGroups Extension repo 
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscore
    branches: [master, 'axon-jgroups-*', '!axon-jgroups-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-jobrunrpro.git  # include docs for Axon JobRunrPro Extension repo 
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscorej
    branches: [master, 'axon-jobrunrpro-*', '!axon-jobrunrpro-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-kafka.git  # include docs for Axon Kafka Extension repo 
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscorej
    branches: [master, 'axon-kafka-*', '!axon-kafka-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-kotlin.git  # include docs for Axon Kotlin Extension repo 
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscorej
    branches: [master, 'axon-kotlin-*', '!axon-kotlin-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-mongo.git  # include docs for Axon MongoDB Extension repo 
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscorej
    branches: [main, 'axon-mongo-*', '!axon-mongo-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-multitenancy.git  # include docs for Axon Multitenancy Extension repo 
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscorej
    branches: [main, 'axon-multitenancy-*', '!axon-multitenancy-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-reactor.git  # include docs for Axon Reactor Extension repo 
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscorej
    branches: [main, 'axon-reactor-*', '!axon-reactor-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-spring-aot.git  # include docs for Axon Spring AOT Extension repo 
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscorej
    branches: [main, 'axon-spring-aot-*', '!axon-spring-aot-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-springcloud.git  # include docs for Axon Spring Cloud Extension repo 
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscorej
    branches: [main, 'axon-springcloud-*', '!axon-springcloud-4.{0..9}.x']

  - url: https://github.com/AxonFramework/extension-tracing.git  # include docs from Axon Tracing Extension repo
    start_paths: ['docs/*', '!docs/_*']                          # from every folder in `docs` except those starting with underscore
    branches: [main, 'axon-tracing-*', '!axon-tracing-4.{0..9}.x']

  - url: https://github.com/AxonIQ/axon-server.git            # include docs from Axon Server repo
    start_paths: ['docs/*', '!docs/_*', '!docs/as-fundamentals-tutorial']                       # from every folder in `docs` except those starting with underscore
    branches: [master, 'axonserver-ee-2024.1*', 'axonserver-ee-2024.2*']                   # and from the specified branches

  - url: https://github.com/AxonIQ/axon-server-image-build.git # include docs from Image generation for Axon Server repo (which contiains docs about Axon Server GCP marketplace)
    start_paths: ['docs/*', '!docs/_*']                        # from every folder in `docs` except those starting with underscore
#    branches: [main]                                          # and from the specified branches


  - url: https://github.com/AxonIQ/axon-synapse.git           # include docs from Axon Synapse repo
    start_paths: ['docs/*', '!docs/_*']                       # from every folder in `docs` except those starting with underscore
    branches: ['synapse-*']                           # and from the specified branches

  - url: https://github.com/AxonIQ/console-web.git            # include docs from AxonIQ Console
    start_paths: ['docs/*', '!docs/_*']                       # from every folder in `docs` except those starting with underscore
    branches: [main]
        
  - url: https://github.com/AxonIQ/bike-rental-quick-start.git          # include docs from Bike Rental Demo App
    start_paths: ['docs/*', '!docs/_*']                                 # from every folder in `docs` except those starting with underscore

  - url: https://github.com/AxonIQ/axoniq-playbook.git          # include docs from Bike Rental Demo App
    start_paths: ['docs/*', '!docs/_*']                                 # from every folder in `docs` except those starting with underscore

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    kroki-server-url: http://localhost:8000
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
  - '@asciidoctor/tabs'

antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js
  - id: prose-linting
    require: '@axoniq/antora-vale-extension'
    enabled: true
    vale_config: .vale.ini
    update_styles: true
  - id: lunr
    require: '@antora/lunr-extension'
    enabled: true
    index_latest_only: true
  # build a site manifest to be used by partial builds
  - id: atlas
    require: '@antora/atlas-extension'

runtime:
  fetch: true # fetch remote repos
  log:
    level: info
    failure_level: error

ui:
  bundle:
    url: https://github.com/AxonIQ/axoniq-library-ui/releases/download/v.0.1.41/ui-bundle.zip
