site:
  title: 📚 AxonIQ Library
  start_page: home::index.adoc

content:
  sources:
  - url: .
    start_paths: components/*
  - url: .
    start_paths: external_repos/axon_framework/*/docs/*
  - url: .
    start_paths: external_repos/axon_server/docs/*
  - url: .
    start_paths: external_repos/axoniq_cloud/docs/*
  - url: .
    start_path: external_repos/giftcard-demo/docs
  - url: ../reference-guide


asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    kroki-fetch-diagram: false
  extensions:
  - asciidoctor-kroki

# ui:
#   bundle:
#     url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
#     snapshot: true
antora:
  extensions:
  - id: banner
    require: ./extensions/banner.js
  - id: build_time
    require: ./extensions/build_time.js

ui:
  bundle:
    url: ./../documentation-ui/build/ui-bundle.zip
