= Download

Downloading and executing a single instance of Axon Server is a simple process.
This guide will walk you through the steps to download and run Axon Server on your local machine.

== Prerequisites

Make sure you have the Java Runtime Environment (JRE) installed on your machine.
Axon Server requires at least Java 17.

If the following command returns a version number, you have Java installed:

[source,bash]
----
java -version
----

Make sure the version of this command is at least 17.

== Step 1: Download

Download Axon Server from our link:https://www.axoniq.io/download[Download Page].
After filling in your email address, you will receive the link in your email.
If you would like, you can also receive notifications about future trainings.

== Step 2: Extract the ZIP

Extract the downloaded ZIP in the installation directory of your choice.

== Step 3: Configure

Axon Server runs with adequate defaults.
However, you can customize it by editing the `axonserver.properties` file in the same directory as the JAR.

include::partial$step-configure.adoc[]

[NOTE]
If you want your Axon Server to be accessible from other machines, you need to add additional settings so machines know
where to find each other. For more information, see the xref:axon-server-installation::extra/hosts-and-connections.adoc[hosts and connections].


== Step 4: AxonIQ Console (optional)

include::partial$step-axoniq-console.adoc[]

== Step 5: Run

To run Axon Server, execute the following command in the installation directory:

[source,bash]
----
java -jar axonserver.jar
----

Once you see the following log line, Axon Server is up and running:

[source]
----
io.axoniq.axonserver.AxonServer: Started AxonServer in 29.056 seconds
----

You can now access the Axon Server dashboard by navigating to link:http://localhost:8024[localhost:8024] in your browser.
If you customized the port, use the custom port instead.

== Step 6: Initialize

include::partial$initialize-standalone.adoc[]


include::partial$step-configure-axon-framework-single.adoc[]