= AxonIQ Developer Installation Guide

The AxonIQ Developer edition of Axon Server is entirely free to use.
It is limited to a single node, and does not include the enterprise features of the AxonIQ Professional and Enterprise editions.

== Additional functionality

You can unlock additional functionality for your Axon Server by connecting it to xref:axoniq-console-reference::index.adoc[AxonIQ Console].
This is free and simple to achieve.

include::partial$console-additional-functionality.adoc[]

This is all free up to 10 connected applications at a time. For more than 10 connected applications, you will need to upgrade to the AxonIQ Professional or Enterprise editions.

[NOTE]
====
Are you going to use Axon Server in a production environment?
Then you should consider using the AxonIQ Professional or Enterprise editions to get a multiple-node cluster
that's highly available. Click link:https://www.axoniq.io/pricing[here] to learn more about the different editions.
====

== Installation methods

You can install AxonIQ Developer in the following ways:

* xref:developer/download.adoc[Download and run]
* xref:developer/ubuntu.adoc[Install on Ubuntu via APT package manager]
* xref:developer/docker.adoc[Run via Docker]
* xref:developer/docker-compose.adoc[Run via Docker Compose]
* xref:developer/kubernetes.adoc[Run on Kubernetes]