= Linux

You can install Axon Server through the package manager integrated into your Linux distribution: APT on Debian and Debian-based distributions (such as Ubuntu), or DNF/YUM on RHEL-based distributions.
Using this method will make it simple to update using commands as well.

[NOTE]
====
The package currently supports Debian 12 (Bookworm) and 13 (Trixie), Ubuntu 22.04 (Jammy) and 24.04 (Noble Numbat), and RHEL 8, 9, and 10 (or compatible distributions, such as Rocky Linux and AlmaLinux).
More distributions will be supported in the future.
====

== Step 1: Installation

Pick the tab that matches your distribution.

include::partial$linux-install-steps.adoc[]

== Step 2: Configure

Axon Server runs with adequate defaults.
However, you can customize it by editing the `/etc/axonserver/axonserver.properties` file that was just installed on your machine.

include::partial$step-configure.adoc[]

[NOTE]
If you want your Axon Server to be accessible from other machines, you need to add additional settings so machines know
where to find each other. For more information, see the xref:axon-server-installation::extra/hosts-and-connections.adoc[hosts and connections].


== Step 3: Axoniq Console (optional)

include::partial$step-axoniq-console.adoc[]

== Step 4: Run Axon Server

You can now start Axon Server!
You can use Systemd if your system uses it:

[source,bash]
----
sudo systemctl start axonserver
----

Or, alternatively, you can run it manually:

[source,bash]
----
sudo -i -u axonserver
cd /var/lib/axonserver/
sh start-axonserver.sh
----

== Step 5: Initialize

include::partial$initialize-standalone.adoc[]

include::partial$step-configure-axon-framework-single.adoc[]
