= Ubuntu

You can install Axon Server through the APT package manager integrated into Ubuntu.
Using this method will make it simple to update using commands as well.

[NOTE]
====
The package currently only supports Ubuntu 22 (Jammy) and 24 (Focal).
More distributions will be supported in the future.
====

== Step 1: Installation

include::partial$ubuntu-install-steps.adoc[]

== Step 5: Configure

Axon Server runs with adequate defaults.
However, you can customize it by editing the `/etc/axonserver/axonserver.properties` file that was just installed on your machine.

include::partial$step-configure.adoc[]

[NOTE]
If you want your Axon Server to be accessible from other machines, you need to add additional settings so machines know
where to find each other. For more information, see the xref:axon-server-installation::extra/hosts-and-connections.adoc[hosts and connections].


== Step 6: AxonIQ Console (optional)

include::partial$step-axoniq-console.adoc[]

== Step 7: Run Axon Server

You can now start Axon Server!
You can use Systemd if your system uses it:

[source,bash]
----
sudo systemctl start axonserver
----

Or, alternatively, you can run it manually:

[source,bash]
----
sudo -i -u axonserver
cd /var/lib/axonserver/
sh start-axonserver.sh
----

== Step 8: Initialize

include::partial$initialize-standalone.adoc[]

include::partial$step-configure-axon-framework-single.adoc[]