= FAQ for Axon Server

pass:[<!-- vale Google.Passive = NO -->]
pass:[<!-- vale Google.Will = NO -->]
pass:[<!-- vale Google.We = NO -->]
pass:[<!-- vale Google.FirstPerson = NO -->]
pass:[<!-- vale AxonIQ.AcronymCase = NO -->]
pass:[<!-- vale AxonIQ.Headings = NO -->]



== Q: So, what exactly is Axon Server? 

Answer: Axon Server is a zero-configuration message router and event store. If you’re a Java developer, it works well with Axon Framework-based applications. However, if you’re using Python, Node.js, C# (or any other major programming language), it provides out-of-the-box message routing and event storage.

== Q: What are some of the main features of Axon Server?

Answer: Here’s a short list of features of the Axon Server:

* Out of the box, zero configuration Message Routing

* Event sourcing capabilities with an infinitely scalable Event Store

* Real-time observability and insights into the messages exchanged between your applications
* Role-based Access Control for both users and applications 
* Easy to scale-out and configure within a clustered environment

== Q: How does Axon Server work as an Event Store? 
Answer: Unlike other messaging solutions like Apache Kafka, which only natively provides message routing, Axon Server works as both a message router and an Event Store. As a dedicated Event Store, Axon Server is designed to store events to enable your microservices applications to be event-sourced. This ensures that events are stored durably and indefinitely and provides superior scalability and throughput without complex database tuning.

== Q: Since RDBMs have problems with scalability, let's discuss scale. Can Axon Server handle large-scale event storage needs? 
Answer:  Yes, Axon Server is built to handle large-scale event storage needs with its infinitely scalable event store, which can manage large volumes of events without performance degradation.

== Q: What security features does Axon Server offer? 
Answer: Axon Server includes robust security features such as authentication, authorization, and the ability to integrate with external security providers like LDAP and OAuth for enhanced security measures.

== Q: What happened to the Standard and Enterprise editions of Axon Server?
Answer: Back in 2023, we decided to phase out the Standard edition and replaced it with a single Axon Server JAR. This enabled our customers to easily upgrade to "Enterprise Features" without installing a different artifact. Please refer to our https://www.axoniq.io/pricing[pricing page] for more details.

We love our active developer community. So developers can feel comfortable that our Axon Server Developer plan is and will always remain free.

== Q:  What happened to the Open Source version of Axon Server?
Answer: We discontinued development of the Open Source version of Axon Server in 2023. Axon Server remains free for development use, but production use requires purchasing one of our plans. Please refer to our https://www.axoniq.io/pricing[pricing page] for more details.



