= FAQ for Axon Server

pass:[<!-- vale Google.Passive = NO -->]
pass:[<!-- vale Google.Will = NO -->]
pass:[<!-- vale Google.We = NO -->]
pass:[<!-- vale Google.FirstPerson = NO -->]
pass:[<!-- vale AxonIQ.AcronymCase = NO -->]
pass:[<!-- vale AxonIQ.Headings = NO -->]



== Q: So, what exactly is Axon Server? 

Answer: Axon Server is a zero-configuration message router and event store. If you’re a Java developer, it works well with  Axon Framework-based applications. However, if you’re using Python, Node.js, C# (or any other major programming language), it provides out-of-the-box message routing and event storage.

== Q: What are some of the main features of Axon Server?

Answer: Here’s a short list of features of the Axon Server:

* Out of the box, zero configuration Message Routing

* Event sourcing capabilities with an infinitely scalable Event Store

* Real-time observability and insights into the messages exchanged between your applications
* Role-based Access Control for both users and applications 
* Easy to scale-out and configure within a clustered environment



