= Build AxonIQ Library

Below are the steps to aggregate all content from all sources and produce the final static website for AxonIQ Library.

== Install required tools

 * Install Antora by following the https://docs.antora.org/antora/latest/install/install-antora/[instructions relevant to your system].
 * Install Vale by following the https://vale.sh/docs/vale-cli/installation/[instructions relevant to your system].


== Get the website source code

Start by cloning the https://github.com/AxonIQ/axoniq-library-site[AxonIQ library repository] using your favorite Git client. A command line, as the one below, works too.

[source,console]
----
$ git clone git@github.com:AxonIQ/axoniq-library-site.git
----

You can give the local folder whatever name you wish, but this document refers to it as `axoniq-library-site`. The code in this project is responsible for generating the AxonIQ Library website. What content the site generator includes and where it gets it from depends on the https://docs.antora.org/antora/latest/playbook/[playbook] file used. In the codebase, there are two playbooks:

 * `playbook.yaml` - this is the production build playbook
 * `playbook-dev.yaml` - this is the playbook configured for building a local development version of the site

IMPORTANT: You shouldn't need to change any of those files. In the rare cases when you may need to, *change both accordingly* to ensure identical results in both environments.

[.no-prose-lint]
== Install Vale packages

The prose linter uses rules from third parties distributed via https://vale.sh/hub/[Vale's Package Hub]. To install those packages, run the following command in the `axoniq-library-site` folder.

[source,console]
----
$ vale sync
----

== Build with production configuration

You can build AxonIQ Library locally with the production configuration to ensure you have all the tooling in place and properly configured. To do so, go to the `axoniq-library-site` folder and run the following command.

[source,console]
----
$ npx antora playbook.yaml
----

IMPORTANT: As described in the https://docs.antora.org/antora/latest/install/install-antora/[instructions to install Antora], make sure you are running a *LTS version of Node.js*

The above uses the `playbook.yaml`, where the locations of the content sources are remote Git repositories. Therefore the build may take a while as the site generator needs to fetch all remote repositories containing content sources.

=== Access to private repositories

Some of the content sources are private repositories that need authentication. You likely only have access to those if you are an AxonIQ employee or a trusted collaborator. If you aren't, you can still build most of the AxonIQ Library locally by making a copy of `playbook.yaml` and removing all the private content sources.

If you are a member of the https://github.com/AxonIQ[AxonIQ Organization on GitHub], you must grant the build tool access to private repositories. To do so, you must create a Personal Access Token (PAT).

 - log in to GitHub
 - go to menu:Settings[Developer settings > Personal access tokens > https://github.com/settings/tokens?type=beta[Fine-grained personal access tokens]]  page and create a new PAT
 - in `Resource owner` select `AxonIQ`
 - in `Repository access` select `All repositories`
 - in `Repository permissions` select *read-only* access to `Contents` and `Metadata`
 - save the PAT and wait for AxonIQ Organizations admins to approve it

Then you need to configure Git to use the PAT. Create or edit the `~/.git-credentials` file and add the following line

[source]
----
https://<USER_NAME>:<ACCEESS_TOKEN>@github.com
----

Replace `<USER_NAME>` with your user name and `<ACCEESS_TOKEN>` with the full PAT you created __(starting with `github_pat_`)__.
With that in place, you can fetch content from private repositories and build the AxonIQ Library locally from the production playbook.

TIP: For alternative ways to configure access to content sources, check Antora's https://docs.antora.org/antora/latest/playbook/private-repository-auth/[Private Repository Authentication] page


== Build with local development configuration

In the `playbook-dev.yaml`, the locations of the content sources are the local Git clones of the respective projects. Thus users need to configure the correct locations for their local machines. The configuration relies on symlinks in a dedicated folder named `localLinks`. This way, `playbook-dev.yaml` doesn't need to change per user.


=== Configure content sources

When you first clone the repository, the `axoniq-library-site/localLinks` folder should be empty. You need to create the respective symlinks to the local Git clones of the projects containing content sources. It's best to explain with an example. Consider the following fragment from `playbook-dev.yaml`.

[source, yaml]
----
  - url: .
    start_paths: ['localLinks/AxonFramework/docs/*', '!localLinks/AxonFramework/docs/playbook']
----

The site builder thus expects all folders under `axoniq-library-site/localLinks/AxonFramework/docs` except `axoniq-library-site/localLinks/AxonFramework/docs/playbook` to be content sources.

Let's assume your local Git clone of Axon Framework is in the `~/work/axon-framework/` folder. Thus the actual path to the content sources on your machine is `~/work/axon-framework/docs`. To satisfy the site builder's expectations, you must create a symlink `axoniq-library-site/localLinks/AxonFramework` that points to `~/work/axon-framework/`. You can do so on Linux and Mac OS with the following command.

[source,console]
----
$ cd axoniq-library-site/localLinks
$ ln -s ~/work/axon-framework/ AxonFramework
----

==== Mixing content sources

It's possible that you don't have local clones of all repositories containing content sources. If you want to avoid cloning more projects than you work on, you can create a custom playbook and mix the content sources configuration. The process is simple.

 * make a copy of `playbook-dev.yaml`. For this document, let's assume the new name is `my-playbook.yaml`
 * add `my-playbook.yaml` to `.gitignore`
 * create the symlinks for the repositories you have local clones
 * edit the `sources` section of `my-playbook.yaml` and replace each entry for which you don't have a local clone with the equivalent from the `playbook.yaml` file

The following fragment shows a mixed configuration.

[source, yaml]
----
  - url: .
    start_paths: ['localLinks/AxonFramework/docs/*', '!localLinks/AxonFramework/docs/playbook']
  - url: https://github.com/AxonIQ/giftcard-demo.git
    start_paths: ['docs/*', '!docs/playbook']
----

In this playbook, Axon Framework's content sources come from a local clone, while the `giftcard-demo` project's content sources come from a remote repository.

CAUTION: When you use a custom playbook outside version control, you must monitor `playbook-dev.yaml` and manually apply any changes to your custom playbook.

=== Build

To build AxonIQ Library locally with the development configuration, go to the `axoniq-library-site` folder and run Antora with the desired playbook.

[source,console]
----
$ npx antora playbook-dev.yaml
----

The above uses the `playbook-dev.yaml`. You can, of course, use `my-playbook.yaml` or any other instead.


== Run AxonIQ Library locally

Antora generates a static site in `axoniq-library-site/build/site` folder. It doesn't have a web server to run the site on `localhost`. You may access it from your browser via the `file://` protocol, but some links may not work. You must have a web server running on your machine to access the site on a URL like `http://localhost:8080`. You can use any of the popular solutions available on your operating system.

You can also start a simple web server from the `axoniq-library-site/build/site` folder in several different ways. Below are some examples.

.Using Python to serve AxonIQ Library on `localhost:8080`
[source, console]
----
python3 -m http.server 8080
----

.Using NodeJS to serve AxonIQ Library on `localhost:8080`
[source, console]
----
npm install -g http-server
http-server -p 8080
----

.Using PHP to serve AxonIQ Library on `localhost:8080`
[source, console]
----
php -S localhost:8080
----
