= Prerequisite Tools and Knowledge
:page-needs-improvement: stub
:page-needs-stub: This document is a stub. Please expand it with relevant details.

From technical perspective, AxonIQ Library is a somewhat complex content aggregator. While most content editors usually don't need to deal with that level of complexity, it helps to understand and familiarize with the tools used to build the final product.

== The main platform

This project uses https://antora.org/[Antora] to aggregate content from many different sources and display it on the AxonIQ Library pages. Please refer to https://docs.antora.org[Antora's documentation] for more information.

== The content format

Antora processes content written in https://asciidoc.org/[AsciiDoc]. AsciiDoc is a plain text markup language for writing technical content. Please refer to the https://docs.asciidoctor.org/asciidoc/latest/[AsciiDoc Language Documentation] for more information.

== Prose linter

This project uses https://vale.sh/[Vale] which bring code-like linting to prose. Please consult the https://vale.sh/docs/topics/scoping/[Vale's documentation] for more information