= Welcome to AxonIQ library
:page-pagination:

AxonIQ Library is a collection of written resources designed to help developers learn and master Axon framework and Axon Server.

The Library content is divided into four categories.

== Explanations

Those are theoretical materials where we clarify and illuminate particular topics. They are most useful when studying.

xref:home:ROOT:explanations.adoc[This page] lists all explanations, but for your convenience, we also list some of the most poplar ones here

* xref:understanding-axon:ROOT:index.adoc[Understanding Axon]
* xref:concepts:ROOT:index.adoc[Understanding the core concepts]

== References

Those are practical technical descriptions of the machinery behind the products. They are most valuable when you work with a product and need to check for the intended usage, available functionality, or configuration options.

xref:home:ROOT:references.adoc[This page] lists all references, but for your convenience, we also list some of the most poplar ones here

* xref:axon_framework_ref:ROOT:index.adoc[]
* xref:axon_server_ref:ROOT:index.adoc[]
* xref:axoniq_cloud_ref:ROOT:index.adoc[]

== Tutorials

Those are theoretical materials where we take you through a series of steps to complete a task. They are most useful when studying or prototyping a new solution.

xref:home:ROOT:tutorials.adoc[This page] lists all tutorials, but for your convenience, we also list some of the most poplar ones here

* xref:giftcard:ROOT:index.adoc[Axon Framework - from design to deployment]
* xref:af_customization:ROOT:index.adoc[Customizing Axon Framework]
* xref:as_admin:ROOT:index.adoc[Axon Server Administration]

== How-to guides

Those are practical guides where we tell you how to solve specific real-world problems step by step. They are most valuable when you work with a product and need a solution for a common task.

xref:home:ROOT:howtos.adoc[This page] lists all how-to guides, but for your convenience, we also list some of the most poplar ones here

* xref:ac_howtos:ROOT:index.adoc[AxonIQ Cloud Console How-to Guides]
