= Welcome To AxonIQ Library
:page-pagination:

AxonIQ Library is a collection of written resources designed to help developers learn and master the products AxonIQ and the software design and development concepts those products assist with.

The Library content is divided into four categories.

== Explanations

Those are theoretical materials where we clarify and illuminate particular topics. They are essential when studying the field or looking for a higher-level overview.

You will find a list of all such materials on the xref:home:ROOT:explanations.adoc[explanations page]. Some of the most popular ones are:

* xref:understanding-axon:ROOT:index.adoc[Understanding Axon]
* xref:concepts:ROOT:index.adoc[Understanding the core concepts]

== References

Those are practical technical descriptions of the machinery behind the products. They prove valuable when you work with a product and need to check for the intended usage, available functionality, or configuration options.

You will find a list of all such materials on the xref:home:ROOT:references.adoc[references page]. Some of the most popular ones are:

* xref:axon_framework_ref:ROOT:index.adoc[]
* xref:axon_server_ref:ROOT:index.adoc[]
* xref:axoniq_cloud_ref:ROOT:index.adoc[]

== Tutorials

Those theoretical materials provide examples of achieving typical goals or explain the process of completing routine tasks. They are invaluable when learning how to use the products to design and develop new solutions.

You will find a list of all such materials on the xref:home:ROOT:tutorials.adoc[tutorials page]. Some of the most popular ones are:

* xref:giftcard:ROOT:index.adoc[Axon Framework - from design to deployment]
* xref:af_customization:ROOT:index.adoc[Customizing Axon Framework]
* xref:as_admin:ROOT:index.adoc[Axon Server Administration]

== How-to guides

Those practical guides tell you how to solve specific real-world problems step by step. They are most valuable when you work with a product and need a solution for a common task.

You will find a list of all such materials on the xref:home:ROOT:howtos.adoc[how-to page]. Some of the most popular ones here

* xref:ac_howtos:ROOT:index.adoc[AxonIQ Cloud Console How-to Guides]
