openapi: 3.0.3
info:
  title: Axon Synapse Client Message API
  description: API for Synapse Clients
  version: 1.0.0
paths:
  /v1/commands:
    post:
      operationId: handleCommandMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'synapse-api.yaml#/components/schemas/CommandMessage'
      responses:
        '200':
          description: The result of the command execution
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/CommandResponseMessage'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/Error'
              example:
                code: AXONIQ-0001
                message: Invalid message
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/Error'
              example:
                code: AXONIQ-1302
                message: Context not found
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/Error'
              example:
                code: AXONIQ-1302
                message: Internal server error
  /v1/queries:
    post:
      operationId: handleQueryMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'synapse-api.yaml#/components/schemas/QueryMessage'
      responses:
        '200':
          description: The result of the query execution
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/QueryResponseMessage'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/Error'
              example:
                code: AXONIQ-0001
                message: Invalid message
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/Error'
              example:
                code: AXONIQ-1302
                message: Context not found
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/Error'
              example:
                code: AXONIQ-1302
                message: Internal server error
  /v1/events:
    post:
      operationId: handleEventMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'synapse-api.yaml#/components/schemas/EventMessage'
          application/vnd.axoniq.event.list+json:
            schema:
              $ref: 'synapse-api.yaml#/components/schemas/ListOfEventMessages'
      responses:
        '200':
          description: The acknowledge of the event processing
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/Error'
              example:
                code: AXONIQ-0001
                message: Invalid message
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/Error'
              example:
                code: AXONIQ-1302
                message: Context not found
        '500':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: 'synapse-api.yaml#/components/schemas/Error'
              example:
                code: AXONIQ-1302
                message: Internal server error

