:description: The guides to upgrade to Axon Server 2024.0.0
:navTitle: Upgrading to Axon Server 2024.0.0

= Upgrading to Axon Server 2024.0.0 

Axon Server 2024.0.0 uses an updated version of the H2 database to store the Control DB. This is required to solve some critical issues in the H2 version used in previous Axon Server versions.

When you download Axon Server 2024.0, the package contains a new jar file `controldb-migration.jar`.

For Axon Server to upgrade the Control DB, you need to place this jar file in the working directory of Axon Server (usually the same directory as the axonserver.jar file). When you start Axon Server, it invokes the `controldb-migration.jar` to migrate the Control DB. After the migration, a new DB file is in the same directory as the old Control DB. This new DB is called `axonserver-configdb`, the filename is `axonserver-configdb.mv.db`. The docker image axoniq/axonserver already contains the `controldb-migration.jar`.

== Datasource override

If you have configured the property `spring.datasource.url` in axonserver.properties yourself, you must update the database name before starting Axon Server. Change the name from axonserver-controldb to axonserver-configdb.
For example:
`spring.datasource.url=jdbc:h2:./data/axonserver-controldb;DEFRAG_ALWAYS=true`
Should now look like this:
`spring.datasource.url=jdbc:h2:./data/axonserver-configdb;DEFRAG_ALWAYS=true`

== Configuring the database location

The preferred property to define the location of the configuration database is changed to `axoniq.axonserver.configdb-path`. The property `axoniq.axonserver.controldb-path` is deprecated, but still works for this version.

== Migration of extensions

If you use the OAuth or LDAP extension for Axon Server, replace the jar files in the exts directory with those included in the new extension.

== Upgrade instructions

The 2024.0.0 release is still compatible with previous releases, so you may do a rolling upgrade.
The upgrade should be reasonably straightforward:

- stop the node
- replace axon server jar
- do the steps from above for the Control DB migration and extensions
- start the node
- repeat the procedure for every node in the cluster

