:page-layout: component-list
:page-list_type: none
:page-list_groups: {}
= AxonIQ Docs

AxonIQ Docs is a collection of written resources designed to help developers learn and master the AxonIQ products. The Docs also help developers understand the software design and development concepts the AxonIQ products can help with.

== AxonIQ Playbook

link:../playbook/[AxonIQ Playbook] is a catalogue of patterns to support the AxonIQ community in modeling, implementing and operating event-sourced systems.

Receive updates from the author Marc Klefter about new content in the AxonIQ Playbook by https://share.hsforms.com/1369fk3LQR7WDkMI3afhr5w40luy[signing up]. To discuss event sourcing and event modeling with Marc, http://meetings.hubspot.com/marc-klefter[book a call] in his calendar.

== Basics

Basics offer examples on how to use AxonIQ products to complete routine tasks when designing and developing new solutions.

The xref:home:ROOT:basics.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:bikerental-demo:ROOT:index.adoc[]
* xref:axoniq-console-getting-started:ROOT:index.adoc[]
// * xref:af_customization:ROOT:index.adoc[Customizing Axon Framework]
// * xref:as_admin:ROOT:index.adoc[Axon Server Administration]

== Guides

Guides are recipes and directions for achieving a specific goal. They are intended for readers with a solid understanding of AxonIQ products.
The guides cover xref:home:guides:axon-framework.adoc[Axon Framework] and xref:home:guides:axon-server.adoc[Axon Server].

== Reference

The practical technical descriptions of the machinery behind the AxonIQ products, their intended usage, available functionality, or configuration options.

The xref:home:ROOT:reference.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:axon-framework-reference:ROOT:index.adoc[Axon Framework Reference Guide]
* xref:axon-server-reference:ROOT:index.adoc[Axon Server Reference Guide]
* xref:axoniq-console-reference:ROOT:index.adoc[AxonIQ Console Reference Guide]
// * xref:axoniq_cloud_ref:ROOT:index.adoc[]
