:page-layout: component-list
= AxonIQ Docs

AxonIQ Docs is a collection of written resources designed to help developers learn and master the products AxonIQ and the software design and development concepts those products assist with.

== Reference

Those are practical technical descriptions of the machinery behind the products. They prove valuable when you work with a product and need to check for the intended usage, available functionality, or configuration options.

The xref:home:ROOT:reference.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:axon_framework_ref::index.adoc[Axon Framework Refererence Guide]
//* xref:axon_framework_ref:ROOT:index.adoc[]
// * xref:axon_server_ref:ROOT:index.adoc[]
// * xref:axoniq_cloud_ref:ROOT:index.adoc[]

== Basics

Those theoretical materials provide examples of achieving typical goals or explain the process of completing routine tasks. They're invaluable when learning how to use the products to design and develop new solutions.

The xref:home:ROOT:basics.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:bikerental-demo:ROOT:index.adoc[]
* xref:axoniq-console-getting-started::index.adoc[]
// * xref:af_customization:ROOT:index.adoc[Customizing Axon Framework]
// * xref:as_admin:ROOT:index.adoc[Axon Server Administration]

== Guides

Guides are recipes and directions on how to achieve a specific end. They are intended for readers with a solid understanding.

The guides cover: 

- Axon Framework
- Axon Server
- Migration
