= Welcome To AxonIQ Library breaking a rule

(changed)

AxonIQ Library is a collection of written resources designed to help developers learn and master the products AxonIQ and the software design and development concepts those products assist with.

The Library content falls into four categories.

== Explanations

Those are theoretical materials explaining or clarifying particular topics. They're essential when studying the field or looking for a higher-level overview.

The xref:home:ROOT:explanations.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:understanding-axon:ROOT:index.adoc[Understanding Axon]
* xref:concepts:ROOT:index.adoc[Understanding the core concepts]

== References

Those are practical technical descriptions of the machinery behind the products. They prove valuable when you work with a product and need to check for the intended usage, available functionality, or configuration options.

The xref:home:ROOT:references.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:axon_framework_ref:ROOT:index.adoc[]
// * xref:axon_server_ref:ROOT:index.adoc[]
// * xref:axoniq_cloud_ref:ROOT:index.adoc[]

== Tutorials

Those theoretical materials provide examples of achieving typical goals or explain the process of completing routine tasks. They're invaluable when learning how to use the products to design and develop new solutions.

The xref:home:ROOT:tutorials.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:giftcard:ROOT:index.adoc[]
// * xref:af_customization:ROOT:index.adoc[Customizing Axon Framework]
// * xref:as_admin:ROOT:index.adoc[Axon Server Administration]

== How-to guides

Those practical guides tell you how to solve specific real-world problems step by step. They're most valuable when you work with a product and need a solution for a common task.

The xref:home:ROOT:howtos.adoc[] page contains all such materials. Some of the most popular ones are:

// * xref:ac_howtos:ROOT:index.adoc[AxonIQ Cloud Console How-to Guides]
