= Welcome To AxonIQ Library

AxonIQ Library is a collection of written resources designed to help developers learn and master the products AxonIQ and the software design and development concepts those products assist with.

== Documentation

Those are practical technical descriptions of the machinery behind the products. They prove valuable when you work with a product and need to check for the intended usage, available functionality, or configuration options.

The xref:home:ROOT:documentation.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:axon_framework_ref:ROOT:index.adoc[]
// * xref:axon_server_ref:ROOT:index.adoc[]
// * xref:axoniq_cloud_ref:ROOT:index.adoc[]

== Tutorials

Those theoretical materials provide examples of achieving typical goals or explain the process of completing routine tasks. They're invaluable when learning how to use the products to design and develop new solutions.

The xref:home:ROOT:tutorials.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:bikerental-demo:ROOT:index.adoc[]
// * xref:af_customization:ROOT:index.adoc[Customizing Axon Framework]
// * xref:as_admin:ROOT:index.adoc[Axon Server Administration]
