:page-layout: component-list
:page-list_type: none
:page-list_groups: {}
= AxonIQ Docs

AxonIQ Docs is a collection of written resources designed to help developers learn and master the AxonIQ products. The Docs also help developers understand the software design and development concepts the AxonIQ products can help with.

== Reference

The practical technical descriptions of the machinery behind the AxonIQ products, their intended usage, available functionality, or configuration options.

The xref:home:ROOT:reference.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:axon-framework-reference:ROOT:index.adoc[Axon Framework Reference Guide]
* xref:axon-server-reference:ROOT:index.adoc[Axon Server Reference Guide]
// * xref:axoniq_cloud_ref:ROOT:index.adoc[]

== Basics

Basics offer examples on how to use AxonIQ products to complete routine tasks when designing and developing new solutions.

The xref:home:ROOT:basics.adoc[] page contains all such materials. Some of the most popular ones are:

* xref:bikerental-demo:ROOT:index.adoc[]
* xref:axoniq-console-getting-started:ROOT:index.adoc[]
// * xref:af_customization:ROOT:index.adoc[Customizing Axon Framework]
// * xref:as_admin:ROOT:index.adoc[Axon Server Administration]

== Guides

Guides are recipes and directions for achieving a specific goal. They are intended for readers with a solid understanding of AxonIQ products.

The guides cover: 

- Axon Framework
- Axon Server
- Migration
