= Download

This guide will walk you through the steps to run Axon Server Professional as a cluster of multiple nodes.

[NOTE]
====
You can also use this guide to run all separate instances on a single machine for testing purposes.
In that case, make sure you use different ports for each instance in step 3.
====

== Prerequisites

Make sure you have the Java Runtime Environment (JRE) installed on the machines where you want to install Axon Server.
Axon Server requires at least Java 17.

If the following command returns a version number, you have Java installed:

[source,bash]
----
java -version
----

Make sure the version of this command is at least 17.

== Step 1: Download

Download Axon Server from our link:https://www.axoniq.io/download[Download Page].
After filling in your email address, you will receive the link in your email.
If you would like, you can also receive notifications about future trainings.

== Step 2: Extract the ZIP

Extract the downloaded ZIP in the installation directory of your choice on all machines.
If you are running all nodes on a single machine, extract the ZIP in different directories.

== Step 3: Configure

Axon Server runs with adequate defaults.
However, you can customize it by editing the `axonserver.properties` file in the same directory as the JAR.

include::partial$step-configure.adoc[]

Make sure that if you run multiple instances on a single machine, you use different ports for each instance.

[NOTE]
If you want your Axon Server to be accessible from other machines, you need to add additional settings so machines know
where to find each other. For more information, see the xref:axon-server-installation::extra/hosts-and-connections.adoc[hosts and connections].


== Step 4: AxonIQ Console

include::partial$obtain-console-access-token.adoc[]

Now you have the access token, you can set it in the `axonserver.properties` file.
Add the following line to the file:

[source,properties]
----
axoniq.console.authentication=<your-access-token>
----


== Step 5: Configure ports

include::partial$step-configure-ports.adoc[]

== Step 6: Run

To run Axon Server, execute the following command in the installation directory:

[source,bash]
----
java -jar axonserver.jar
----

Once you see the following log line, Axon Server is up and running:

[source]
----
io.axoniq.axonserver.AxonServer: Started AxonServer in 29.056 seconds
----

Based on information in AxonIQ Console, the cluster will automatically form.

You can now access the Axon Server dashboard by navigating to port 8024 of the machine in your browser.
If you customized the port, use the custom port instead.


include::partial$step-configure-axon-framework-multiple.adoc[]