= Axoniq Professional Installation Guide

The Axoniq Professional edition of Axon Server can be purchased via link:https://console.axoniq.io[Axoniq Console]. This is the edition you want to use when you need a highly available, multiple-node cluster,
but don't need the additional features of the xref:enterprise/index.adoc[Enterprise edition].

== Included functionality

With the Axoniq Professional edition, you get the following features:

- **Multi-node cluster**: A multi-node cluster is a cluster of Axon Server instances that work together to provide a highly available, scalable, and fault-tolerant messaging platform. The Axoniq Professional edition allows you to run a cluster of up to 3 nodes.
- **Multi-context support**: You can create multiple contexts in Axon Server, which provide an isolated messaging environments for different parts of your application.
- **Alerting**: Axoniq Console will monitor your Axon Server instances and alert you when something goes wrong.


[NOTE]
====
Do you require more than three nodes in your cluster, need advanced authentication mechanisms such as LDAP or OAuth, or need 24/7 support?
Then you should consider using the xref:enterprise/index.adoc[Enterprise edition] of Axon Server.
====

== Installation methods

You can install Axoniq Developer in the following ways:

* xref:professional/download.adoc[Download and run]
* xref:professional/linux.adoc[Install on Linux via APT/DNF/YUM package manager]
* xref:professional/docker-compose.adoc[Run via Docker Compose]
* xref:professional/kubernetes.adoc[Run on Kubernetes]
