name: Check Pull Request
on:
  pull_request:
    branches: [main]

jobs:
  check-pull-request:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install vale
      run: |
        wget https://github.com/errata-ai/vale/releases/download/v${{ vars.LIBRARY_VALE_VERSION }}/vale_${{ vars.LIBRARY_VALE_VERSION }}_Linux_64-bit.tar.gz
        sudo tar -xvzf vale_${{ vars.LIBRARY_VALE_VERSION }}_Linux_64-bit.tar.gz -C /usr/local/bin vale
    - name: Install Dependencies
      run: npm install
    - name: Generate Site
      run: |
        export GIT_CREDENTIALS='https://axoniq-devops:${{ secrets.LIBRARY_DEVBOT_TOKEN }}@github.com'
        echo 'Using' `vale -v`
        npx antora playbook.yaml
