name: Publish to GitHub Pages
on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  VALE_VERSION: ${{ vars.LIBRARY_VALE_VERSION || '3.3.0' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    - name: Install Antora
      run: |
        npm i antora
        npx antora -v
    - name: Install vale
      run: |
        wget https://github.com/errata-ai/vale/releases/download/v${VALE_VERSION}/vale_${VALE_VERSION}_Linux_64-bit.tar.gz
        sudo tar -xvzf vale_${VALE_VERSION}_Linux_64-bit.tar.gz -C /usr/local/bin vale
        npm install @axoniq/antora-vale-extension
    - name: Generate Site
      run: |
        export GIT_CREDENTIALS='https://axoniq-devops:${{ secrets.LIBRARY_DEVBOT_TOKEN }}@github.com'
        echo 'Using' `vale -v`
        npx antora playbook.yaml --log-level debug
    - name: Create `.nojekyll`
      run: touch build/site/.nojekyll
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/site
