name: Publish to GitHub Pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Antora
      run: npm i antora
    - name: Install vale
      run: |
        wget https://github.com/errata-ai/vale/releases/download/v2.23.0/vale_2.23.0_Linux_64-bit.tar.gz
        mkdir bin && tar -xvzf vale_2.23.0_Linux_64-bit.tar.gz -C bin
        export PATH=./bin:"$PATH"
    - name: Generate Site
      run: npx antora playbook.yaml
    - name: Create `.nojekyll`
      run: touch build/site/.nojekyll
    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/site
